---
- name: Install nginx
  apt:
    pkg:
      - nginx
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Init nginx
  service:
    name: nginx
    state: started

- name: create dir /app
  file:
    path: /app
    state: directory

- name: copy package.json
  copy:
    src: package.json
    dest: /app/package.json

- name: npm Install
  npm:
    path: /app
    state: present

- name: copy index.js
  template:
    src: index.js.j2
    dest: /app/index.js
#   template:
#     src: nginx.conf.j2
#     dest: /etc/nginx/sites-available/default
#   notify: reload nginx
